
import Database.DatabaseConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acer
 */
public class ResultsPanel extends javax.swing.JFrame {

    /**
     * Creates new form ResultsPanel
     */
    public ResultsPanel() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        getFirstData();
        getPercentageDtata();
        getRatingData();
    }
    
    private void getFirstData(){
        
        try{
            Connection conn = DatabaseConnection.getConn();
            Statement st = conn.createStatement();
            String string =   "SELECT COUNT(*) AS total,"
                            + "ROUND(CAST(AVG(age)AS FLOAT),1) AS avg_age,"
                            + "MAX(age) AS max_age,"
                            + "MIN(age) AS min_age FROM user_info";
            ResultSet result = st.executeQuery(string);
            
            if(result.next()){
                totalSurvey.setText(result.getString("total")+" ");
                avgAge.setText(result.getString("avg_age")+" ");
                maxAge.setText(result.getString("max_age")+" ");
                minAge.setText(result.getString("min_age")+" ");
                
               
            }
                
            
            
        }catch(Exception e){
            
        }
        
    }
    
    private void getPercentageDtata(){
        
        try{
            
            Connection conn = DatabaseConnection.getConn();
            Statement st = conn.createStatement();
            String st1 = "SELECT (SELECT ROUND(CAST((COUNT(fav_food)*100/(SELECT COUNT(*) FROM user_info)) AS FLOAT),1) FROM user_info WHERE fav_food LIKE '%pizza%') AS PizzaPerc,";
            String st2 = "(SELECT ROUND(CAST((COUNT(fav_food)*100/(SELECT COUNT(*) FROM user_info)) AS FLOAT),1) FROM user_info WHERE fav_food LIKE '%pasta%') AS PastaPerc,";
            String st3 = "(SELECT ROUND(CAST((COUNT(fav_food)*100/(SELECT COUNT(*) FROM user_info))AS FLOAT),1) FROM user_info WHERE fav_food LIKE '%pap%') AS PapPerc FROM user_info LIMIT 1";
                    
            ResultSet result = st.executeQuery(st1+st2+st3);
            
            if(result.next()){
                
                pizzaPerc.setText(result.getString("PizzaPerc")+" % ");
                pastaPerc.setText(result.getString("PastaPerc")+" % ");
                papPerc.setText(result.getString("PapPerc")+" % ");
                
              
            }
        }catch(Exception e){
            
             JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }
    
    private void getRatingData(){
        
        try{ 
            
            Connection conn = DatabaseConnection.getConn();
            Statement st = conn.createStatement();
            String sqlQuery = "SELECT ROUND(CAST(AVG(eat_out) AS FLOAT),1) as avgEatRate,"
                            + "ROUND(CAST(AVG(watch_movie)AS FLOAT),1) AS avgMovieRate,"
                            + "ROUND(CAST(AVG(watch_tv)AS FLOAT),1) AS avgTvRate,"
                            + "ROUND(CAST(AVG(listen_to_radio)AS FLOAT),1) AS avgRadioRate FROM hobby";
            
            ResultSet result = st.executeQuery(sqlQuery);
            
            if(result.next()){
                avgRateEat.setText(result.getString("avgEatRate")+" ");
                avgRateMov.setText(result.getString("avgMovieRate")+" ");
                avgRateTv.setText(result.getString("avgTvRate")+" ");
                avgRateRadio.setText(result.getString("avgRadioRate")+" ");
            }
        
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        papPerc = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        totalSurvey = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        avgAge = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        maxAge = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        minAge = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        pizzaPerc = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pastaPerc = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        avgRateEat = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        avgRateRadio = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        avgRateMov = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        avgRateTv = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Results and Statistic");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 204, 0));
        jButton1.setText(" ok  ");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 620, 209, 38));

        jPanel2.setBackground(new java.awt.Color(255, 0, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Percentage of people who like pap and wors");
        jLabel13.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        papPerc.setFont(new java.awt.Font("Yu Gothic Medium", 3, 14)); // NOI18N
        papPerc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        papPerc.setText("  result  ");
        jPanel2.add(papPerc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 70, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 330, 100));

        jPanel4.setBackground(new java.awt.Color(255, 204, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 0, 3, new java.awt.Color(255, 255, 255)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Total number of survey");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 150, -1));

        totalSurvey.setFont(new java.awt.Font("Yu Gothic Medium", 3, 14)); // NOI18N
        totalSurvey.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalSurvey.setText(" result  ");
        jPanel4.add(totalSurvey, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 70, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 330, 100));

        jPanel6.setBackground(new java.awt.Color(0, 153, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 3, new java.awt.Color(255, 255, 255)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Average age");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        avgAge.setFont(new java.awt.Font("Yu Gothic Medium", 3, 14)); // NOI18N
        avgAge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avgAge.setText("  result  ");
        jPanel6.add(avgAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 70, 30));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 330, 100));

        jPanel5.setBackground(new java.awt.Color(255, 0, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 3, new java.awt.Color(255, 255, 255)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Oldest person who participated in survey");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        maxAge.setFont(new java.awt.Font("Yu Gothic Medium", 3, 14)); // NOI18N
        maxAge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maxAge.setText("  result  ");
        jPanel5.add(maxAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 70, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 330, 100));

        jPanel7.setBackground(new java.awt.Color(255, 51, 51));
        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minAge.setFont(new java.awt.Font("Yu Gothic Medium", 3, 14)); // NOI18N
        minAge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minAge.setText("  result  ");
        jPanel7.add(minAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 70, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Youngest person who participated in survey");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 330, 100));

        jPanel8.setBackground(new java.awt.Color(0, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 0, 3, new java.awt.Color(255, 255, 255)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Percentage of people who like pizza");
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        pizzaPerc.setFont(new java.awt.Font("Yu Gothic Medium", 3, 14)); // NOI18N
        pizzaPerc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pizzaPerc.setText("  result   ");
        jPanel8.add(pizzaPerc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 70, 30));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 330, 100));

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 3, new java.awt.Color(255, 255, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pastaPerc.setFont(new java.awt.Font("Yu Gothic Medium", 3, 14)); // NOI18N
        pastaPerc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pastaPerc.setText("  result  ");
        jPanel1.add(pastaPerc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 70, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Percentage of people who like pasta");
        jLabel11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 330, 100));

        jPanel9.setBackground(new java.awt.Color(255, 51, 51));
        jPanel9.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 0, 3, new java.awt.Color(255, 255, 255)));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("People like to eat out");
        jLabel12.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        avgRateEat.setFont(new java.awt.Font("Yu Gothic Medium", 3, 14)); // NOI18N
        avgRateEat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avgRateEat.setText("  result  ");
        jPanel9.add(avgRateEat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 70, 30));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 130, 330, 100));

        jPanel3.setBackground(new java.awt.Color(255, 204, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("People like to listen to radio");
        jLabel19.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 170, -1));

        avgRateRadio.setFont(new java.awt.Font("Yu Gothic Medium", 3, 14)); // NOI18N
        avgRateRadio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avgRateRadio.setText("  result  ");
        jPanel3.add(avgRateRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 70, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 430, 330, 100));

        jPanel10.setBackground(new java.awt.Color(255, 0, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 3, new java.awt.Color(255, 255, 255)));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        avgRateMov.setFont(new java.awt.Font("Yu Gothic Medium", 3, 14)); // NOI18N
        avgRateMov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avgRateMov.setText("  result  ");
        jPanel10.add(avgRateMov, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 70, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("People like to watch movies");
        jLabel17.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel10.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 230, 330, 100));

        jLabel6.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Programming test intern");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 650, -1, -1));

        jPanel11.setBackground(new java.awt.Color(0, 153, 0));
        jPanel11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 3, new java.awt.Color(255, 255, 255)));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        avgRateTv.setFont(new java.awt.Font("Yu Gothic Medium", 3, 14)); // NOI18N
        avgRateTv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avgRateTv.setText("  result  ");
        jPanel11.add(avgRateTv, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 70, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("People like to watch TV");
        jLabel18.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel11.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 330, 330, 100));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgroundImages/Ads_Q3-2021-Forrester-Wave_MX-Blog-Header-1500-x-700-1(0).jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1510, -530, 3130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

       
        new HomeScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultsPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avgAge;
    private javax.swing.JLabel avgRateEat;
    private javax.swing.JLabel avgRateMov;
    private javax.swing.JLabel avgRateRadio;
    private javax.swing.JLabel avgRateTv;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel maxAge;
    private javax.swing.JLabel minAge;
    private javax.swing.JLabel papPerc;
    private javax.swing.JLabel pastaPerc;
    private javax.swing.JLabel pizzaPerc;
    private javax.swing.JLabel totalSurvey;
    // End of variables declaration//GEN-END:variables
}
